### ISSUE TITLE
Basic Visualisation

### ISSUE THREAD

**Issue by mguru1998** [jaibhageria/Agrolyzer#2]
Please upload the file depicting basic visualisation and insights from the various attributes.

**Comment by jaibhageria** [comment]
Uploaded files having code for Visualisation of dataset with piecharts
Visualised districts and crops distribution with maps
Also found some basic insights like best crop for each state and best crop for each season
Files uploaded:
Visualisation&Insights.R (Contains the R code to form pie-charts and display some basic insights)
Maps.R(Contains the code to draw the maps)
DA_Agro_Top10-pie1.jpeg (Pie chart to display top 10 crops according to production)
DA_Agro_Top10-pie2.jpeg(Pie chart to display top 10 crops according to area)
Farming_Districts_2000.pdf(Map to display the farming districts in the year 2000)
India_Map_Crops_2000.html(Interactive map which shows distribution of all crops in India for the year 2000)
